### ISSUE TITLE
Discovery not working

### ISSUE THREAD

**Issue by gngj** [cmroche/greeclimate#23]
since https://github.com/cmroche/greeclimate/pull/15 discovery of a "tadiran supreme 340" that is a gree device is not working.
It is not responding to 255.255.255.255 address.

testded with greeclimate 0.9.0 and it worked fine.

**Comment by cmroche** [comment]
@gngj There was an important bug fix made on 0.10.1 which address some devices not binding. Please try with at least that version first.

Run the following tests:

`gree.py --discovery`

And paste the output.

**Comment by cmroche** [comment]
@gngj To help with my request above, I've added some instructions to the readme: https://github.com/cmroche/greeclimate#debugging

**Comment by cmroche** [comment]
@gngj Any luck?

**Comment by cmroche** [comment]
@gngj I'm going to close the ticket since I have not heard back. The change in broadcast emulates what is done in the Gree+ app, so if you continue to have problems we can look at it, but I suspect there might be another problem at play.
