### ISSUE TITLE
Wrong temperature returned on v1 software

### ISSUE THREAD

**Issue by lgm42** [cmroche/greeclimate#34]
My device returns me a -17°C temperature value.
This value correspond to 23°C (the real one) - 40.
Here is my installation information:

`
{"t": "pack", "i": 0, "uid": 0, "cid": "XXXXXXXX", "tcid": "app", "pack": {"t": "dat", "uid": 0, "cid": "XXXXXXXX", "mac": "XXXXXXXX", "cols": ["hid"], "dat": ["362001000835+U-CS532AX(MTK)V1.bin"], "r": 200}}
`

I can find the software is v1 and temp - 40 computation is applied if v != 4.
To confirm I have made a little "print" insertion in the current_temperature prop :

```
@property
    def current_temperature(self) -> int:
        prop = self.get_property(Props.TEMP_SENSOR)
        bit = self.get_property(Props.TEMP_BIT)
        if prop is not None:
            v = self._version and int(self._version.split(".")[0])
            print(f"*******version {v}")
            print(f"*******prop {prop}")
            if v == 4:
                return self._convert_to_units(prop, bit)
            elif prop != 0:
                return self._convert_to_units(prop - 40, bit)

        return self.target_temperature
```

Here is my output

```
*******version 1
*******prop 23
```

I should obtain 23°C but I still obtain -17°C.

Any idea of what i can do ?

**Comment by cmroche** [comment]
Hi, thanks for the info. I'll add this firmware into the special cases so that it is handled in the next release.

**Comment by cmroche** [comment]
Will be part of release 0.11.9

**Comment by cmroche** [comment]
https://github.com/home-assistant/core/pull/57358

**Comment by RichardTHF** [comment]
Hi there, 

So I am having the same issue where within HA it is displaying a negative temperature (-17 when it should be 23). 

@lgm42 I see you have modified the current_temperature property, I am new to HA, where do I need to go to find this? (Sorry for the noob question).

**Comment by cmroche** [comment]
@RichardTHF I need the “HID” identifier from your device. Easiest way to get that right now is to enable debug logging in HA.

Add this to your configuration.yaml

```yaml
logger:
  logs:
    homeassistant.components.gree: debug
    greeclimate: debug
```

Restart your HA, and shortly after the device connects and does the initial update you can check your logs and copy and paste the whole thing here. I’ll be able to pull the firmware version out from that.
