### ISSUE TITLE
Discovery not working

### ISSUE THREAD

**Issue by faith0811** [cmroche/greeclimate#39]
Might not be the same with https://github.com/cmroche/greeclimate/issues/23
I downgraded to 0.9.0, and modified some code, still couldn't get it working.

In the current version, the ``python gree.py --discovery`` returns
```
asyncio - DEBUG - Using selector: EpollSelector
__main__ - DEBUG - Scanning network for Gree devices
greeclimate.discovery - INFO - Scanning for Gree devices ...
greeclimate.discovery - DEBUG - Listening for devices on 192.168.11.137 using 192.168.11.255
greeclimate.discovery - DEBUG - Listening for devices on 172.19.0.1 using 172.19.255.255
greeclimate.discovery - DEBUG - Listening for devices on 172.17.0.1 using 172.17.255.255
greeclimate.network - DEBUG - Sending packet:
{"t": "scan"}
greeclimate.network - DEBUG - Sending packet:
{"t": "scan"}
greeclimate.network - DEBUG - Sending packet:
{"t": "scan"}
__main__ - INFO - Done discovering devices
```

And 0.9.0 returns
```
asyncio - DEBUG - Using selector: EpollSelector
__main__ - DEBUG - Scanning network for Gree devices
greeclimate.discovery - INFO - Starting Gree device discovery process
greeclimate.network - DEBUG - Listening for devices on 172.17.0.1
greeclimate.network - DEBUG - Listening for devices on 172.19.0.1
greeclimate.network - DEBUG - Listening for devices on 192.168.11.137
__main__ - INFO - []
__main__ - INFO - Done discovering devices
```
Neither of these works.
The broadcast packet is sent, but nothing comes back. Here is the tcpdump log
```
10:49:19.355235 IP 192.168.11.137.53634 > 192.168.11.255.7000:  [|rx] (13)
```

My air conditioner is connected to the Gree+ app on iOS, and also operational on iOS. I can get the air conditioner's IP from the router.

Can I get the device information by specifying the IP? Or is there another way to debug it?

Thank you.

**Comment by cmroche** [comment]
@faith0811 Recently I've had a few reports from other users who can get their device to work in Gree+ but not over the network. Newer devices in particular seem to be cloud only and will not work with a local, direct, connection as far as I can tell.

The **gree.py** test util doesn't take a host directly, it was only for testing discovery so far. But you can definitely try creating a device using `DeviceInfo` and supplying an IP address **and** mac address.

If you are able to get a tcpdump directly from the router, or from some device between the router and AC, do a capture connecting from the Gree+ APP and making some varying changes. I should be able to tell if the device is supported with that information.

Please let me know if that is possible.

**Comment by cmroche** [comment]
As there hasn’t been any activity here in a while I’m going to close the issue. But please re-open if you are able to get the information requested, or can add more information that might help validate and isolate a solution. Thanks.
