### ISSUE TITLE
Temperature Sensor Reporting -40 from actual. 

### ISSUE THREAD

**Issue by RichardTHF** [cmroche/greeclimate#40]
Hi, 

The temperature sensor for my three units are returning with a negative value around -40 from what would be expected for the unit in what I believe is the same issue found in issue #34 

I have attached what I believe is the correct log below, but if it isn't please let me know. 

Rich

```
{"t": "pack", "i": 0, "uid": 0, "cid": "780f77ac74ab", "tcid": "app", "pack": {"t": "dat", "uid": 0, "cid": "780f77ac74ab", "mac": "780f77ac74ab", "dat": ["362001060297+U-CS532AF(MTK)V2.bin"], "cols": ["hid"], "r": 200}}
```
```
{"t": "pack", "i": 0, "uid": 0, "cid": "780f77af6755", "tcid": "app", "pack": {"t": "dat", "uid": 0, "cid": "780f77af6755", "mac": "780f77af6755", "dat": ["362001060297+U-CS532AF(MTK)V2.bin"], "cols": ["hid"], "r": 200}}
```
```
{"t": "pack", "i": 0, "uid": 0, "cid": "780f779e9cb2", "tcid": "app", "pack": {"t": "dat", "uid": 0, "cid": "780f779e9cb2", "mac": "780f779e9cb2", "dat": ["362001060297+U-CS532AF(MTK)V2.bin"], "cols": ["hid"], "r": 200}}

```

![AC](https://user-images.githubusercontent.com/5789676/147524686-b21535ee-bc4e-4830-bb87-11b8bbe0d987.png)

**Comment by cmroche** [comment]
@RichardTHF Thanks, this has the info I need, I'll make an update over the next day or two.

**Comment by RichardTHF** [comment]
Thank you for fixing! Please add a BuyMeACoffee link to your profile so I can say thank you like that :-)
