### ISSUE TITLE
Add supported feature lists

### ISSUE THREAD

**Issue by cmroche** [cmroche/greeclimate#5]
Not all devices support all features, ie: horizontal swing.

Is it possible to detect unsupported features and build feature lists? This will enable reflected supported functionality through UI much better.

**Comment by cmroche** [comment]
After testing, this doesn't appear to be possible.

When setting a known feature (ie: Health mode) on a device that doesn't support the feature, the response from that device shows the value as still being set.

`Sending packet:
{"cid": "app", "i": 0, "t": "pack", "uid": 0, "tcid": "f4911e7aca59", "pack": {"opt": ["Health"], "p": [1], "t": "cmd"}}`

This gets the response:

`Recived packet:
{"t": "pack", "i": 0, "uid": 0, "cid": "f4911e7aca59", "tcid": "", "pack": {"t": "res", "mac": "f4911e7aca59", "r": 200, "opt": ["Health"], "p": [0], "val": [0]}}`

Even though this feature is not supported on the device.

It might be possible to use device lists to manage this in the future, but that would only enable supported feature setting on devices that were known and manually added to the list.

**Comment by solazs** [comment]
Hey @cmroche 
Would it be possible to add options to the integration to manually configure the supported feature set?
