### ISSUE TITLE
Question: How do I get the current device info

### ISSUE THREAD

**Issue by JtMotoX** [cmroche/greeclimate#55]
I am able to `push_state_update` to **SET** the device info.  But how do I **GET** the current device info?

For example, I want to +2 the current set temperature.  So I need to be able to get the current set temperature (e.g. 20°) so I can add 2° to it and issue a `push_state_update` for 22°.

Another example would be the fan speed.  If the fan speed is 1, then I want to set it to 2.  But before I can do this, I need to know the current fan speed.

**Comment by cmroche** [comment]
Call `device.update_state()`, it's async but once it is done the value should be in `device.target_temperature`

**Comment by JtMotoX** [comment]
@cmroche Wow thanks for the info.  Just tried it out and it works perfectly.  Thanks!
