### ISSUE TITLE
AttributeError: 'Device' object has no attribute 'temperature_unitsTemperatureUnits'

### ISSUE THREAD

**Issue by JtMotoX** [cmroche/greeclimate#57]
I am getting errors when trying to push the state using the class.

https://github.com/JtMotoX/gree-controller/blob/main/build/gree/main.py#L56

---
```python
device.temperature_units = TemperatureUnits.F
```

Result: :x: `AttributeError: 'Device' object has no attribute 'temperature_unitsTemperatureUnits'`

---

```python
device.temperature_units = 1
```

Result: :white_check_mark: Success

---

```python
device.fan_speed = FanSpeed.Auto
```

Result: :x: `NameError: name 'FanSpeed' is not defined`

---

```python
device.fan_speed = 0
```

Result: :white_check_mark: Success

---

**Comment by cmroche** [comment]
I think you are missing imports for the enums, see here:

https://github.com/cmroche/greeclimate/blob/master/greeclimate/device.py#L50

**Comment by JtMotoX** [comment]
I have added the imports but still failing with the same error.

https://github.com/JtMotoX/gree-controller/compare/main...feature/fix-enums?diff=unified

**Comment by cmroche** [comment]
I mean

```python
from greeclimate.devices import FanSpeed, TemperatureUnits
```

**Comment by JtMotoX** [comment]
Ahh, that did it!  Thanks again!

https://github.com/JtMotoX/gree-controller/commit/bbdd7a8f976ccee797a034046bc9129f45a23698?diff=unified
