### ISSUE TITLE
How to increase network timeout

### ISSUE THREAD

**Issue by agroszer** [cmroche/greeclimate#74]
Hi,

Is there any chance to increase network timeout?
I have a few devices on the odd end of the wifi network, which get randomly unavailable with HA.
Or is there some other better solution?

**Comment by cmroche** [comment]
Presently device timeouts are set to 120 seconds. It's pretty unlikely that your network is holding packets for that long, and more likely that they are just being dropped since it's UDP based. Increasing the timeout is unlikely to solve the problem I'm afraid.

**Comment by agroszer** [comment]
ugh, did not know that it's 120 secs.
Yeah if it does not work within 120 secs, then it's hopeless.
