### ISSUE TITLE
second subnet

### ISSUE THREAD

**Issue by massimilianodossi** [cmroche/greeclimate#93]
I have a second subnet configured on home assistant, is it possible to choose which network to search for air conditioners?

**Comment by hawkeye1103** [comment]
I have a second subnet assigned to home assistant as well, and it can't find my gree ac's in that vlan. Better we need a feature to add gree ac's by ip. Point it towards the ip it needs to connect to.

**Comment by cmroche** [comment]
This issue it better tracked on HA as it's a problem only with HA and not the greeclimate lib, there is a thread here: https://github.com/home-assistant/core/issues/95374.

Please note that it's a feature change I intend to work on in the coming weeks. I have a few other issues to resolve first.

**Comment by ggirard07** [comment]
@cmroche any update on that? (sorry for pocking from the lib, but all related issue on HA side seem to be closed and locked due to their bot).
